# Generated by Django 5.1.4 on 2024-12-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minute',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_minute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minute',
            name='marked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minute',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minute',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_minutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
