# Generated by Django 5.1.4 on 2024-12-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_minute_comments_minute_current_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='approval_chain',
            field=models.JSONField(default=list),
        ),
    ]
