# Generated by Django 5.1.4 on 2024-12-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_remove_minute_approval_chain_remove_minute_approvers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
