# Generated by Django 5.1.4 on 2024-12-19 22:10

import apps.minutes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_alter_minute_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='approved',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='minute',
            name='unique_id',
            field=models.CharField(default="TEMP_ID", max_length=20, unique=True),
        ),
    ]
