# Generated by Django 5.1.4 on 2024-12-20 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='chain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='approval_chain.approvalchain'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
